#!/usr/bin/env python3
"""
Download the webfonts the site uses and write assets/css/fonts.css.

The site serves its fonts from its own origin rather than from Google's
CDN. A stylesheet fetched from fonts.googleapis.com sends the visitor's IP
address to Google on every page view, which LG Muenchen I held to be a GDPR
violation absent consent (20 Jan 2022, 3 O 17493/20), and the EU is a target
market for this site.

Google still serves the font files themselves under the SIL Open Font
License, so this fetches them once and rewrites the @font-face rules to
point at local copies. Run it only when a family needs adding or updating -
the result is committed, so a normal build never touches the network.

    python3 scripts/fetch-fonts.py

Variable fonts are requested (a weight *range*, not a list), so one file per
subset covers every weight the design uses.
"""
import os
import re
import subprocess
import sys

FAMILIES = ['Bricolage+Grotesque:opsz,wght@12..96,200..800',
            'Inter:wght@400..700',
            'JetBrains+Mono:wght@400..600']
SUBSETS = {'latin', 'latin-ext'}
FONT_DIR = 'assets/fonts'
CSS_OUT = 'assets/css/fonts.css'

# Google serves woff2 only to browsers that advertise support.
UA = ('Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36')

HEADER = """/* Self-hosted variable webfonts, served from this origin so that no
   visitor IP reaches a third-party CDN - a GDPR requirement in the EU
   markets this site targets (LG Muenchen I, 3 O 17493/20).
   Subsets: latin, latin-ext. One file per subset covers every weight.
   Inter and JetBrains Mono are both SIL Open Font License 1.1.

   Generated by scripts/fetch-fonts.py - do not edit by hand. */

"""


def fetch(url, binary=False):
    cmd = ['curl', '-sSL', '-A', UA]
    ca = os.environ.get('CURL_CA_BUNDLE')
    if ca:
        cmd += ['--cacert', ca]
    out = subprocess.run(cmd + [url], capture_output=True)
    if out.returncode != 0:
        sys.exit('error: could not fetch %s\n%s'
                 % (url, out.stderr.decode('utf-8', 'replace').strip()))
    return out.stdout if binary else out.stdout.decode('utf-8')


def main():
    url = ('https://fonts.googleapis.com/css2?'
           + '&'.join('family=' + f for f in FAMILIES) + '&display=swap')
    css = fetch(url)

    blocks = re.findall(r'/\*\s*([a-z0-9-]+)\s*\*/\s*(@font-face\s*\{.*?\})', css, re.S)
    if not blocks:
        sys.exit('error: no @font-face rules in the stylesheet Google returned')

    os.makedirs(FONT_DIR, exist_ok=True)
    faces, written = [], {}
    for subset, face in blocks:
        if subset not in SUBSETS:
            continue
        family = re.search(r"font-family:\s*'([^']+)'", face).group(1)
        weight = re.search(r'font-weight:\s*([\d\s]+);', face).group(1).strip()
        remote = re.search(r'url\((https://[^)]+\.woff2)\)', face).group(1)

        name = '%s-%s.woff2' % (family.lower().replace(' ', '-'), subset)
        path = os.path.join(FONT_DIR, name)
        if name not in written:
            with open(path, 'wb') as f:
                f.write(fetch(remote, binary=True))
            written[name] = os.path.getsize(path)

        face = face.replace(remote, '../fonts/' + name)
        faces.append('/* %s %s %s */\n%s'
                     % (family, weight, subset, re.sub(r'\n\s*', '\n  ', face.strip())))

    if not faces:
        sys.exit('error: none of the requested subsets (%s) were served'
                 % ', '.join(sorted(SUBSETS)))

    with open(CSS_OUT, 'w', encoding='utf-8') as f:
        f.write(HEADER + '\n\n'.join(faces) + '\n')

    print('wrote %s (%d faces)' % (CSS_OUT, len(faces)))
    for name, size in sorted(written.items()):
        print('  %-34s %6.1f KB' % (name, size / 1024))
    print('  %-34s %6.1f KB' % ('total', sum(written.values()) / 1024))
    return 0


if __name__ == '__main__':
    sys.exit(main())
